/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ImmiVaultRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accessPrice"
      | "cases"
      | "contributorCases"
      | "getCase"
      | "getContributorCases"
      | "getContributorStats"
      | "hasAccess"
      | "hasPaid"
      | "owner"
      | "payForAccess"
      | "registerCase"
      | "renounceOwnership"
      | "setAccessPrice"
      | "transferOwnership"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessPriceUpdated"
      | "CaseAccessed"
      | "CaseRegistered"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "accessPrice",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "cases", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "contributorCases",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getCase", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getContributorCases",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContributorStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAccess",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPaid",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payForAccess",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCase",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAccessPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "accessPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cases", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contributorCases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCase", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getContributorCases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributorStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasAccess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasPaid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payForAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAccessPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace AccessPriceUpdatedEvent {
  export type InputTuple = [oldPrice: BigNumberish, newPrice: BigNumberish];
  export type OutputTuple = [oldPrice: bigint, newPrice: bigint];
  export interface OutputObject {
    oldPrice: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CaseAccessedEvent {
  export type InputTuple = [
    cidHash: BytesLike,
    payer: AddressLike,
    contributor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    cidHash: string,
    payer: string,
    contributor: string,
    amount: bigint
  ];
  export interface OutputObject {
    cidHash: string;
    payer: string;
    contributor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CaseRegisteredEvent {
  export type InputTuple = [
    cidHash: BytesLike,
    contributor: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    cidHash: string,
    contributor: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    cidHash: string;
    contributor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ImmiVaultRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ImmiVaultRegistry;
  waitForDeployment(): Promise<this>;

  interface: ImmiVaultRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accessPrice: TypedContractMethod<[], [bigint], "view">;

  cases: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint] & {
        contributor: string;
        accessCount: bigint;
        totalEarned: bigint;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  contributorCases: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getCase: TypedContractMethod<
    [cidHash: BytesLike],
    [
      [string, bigint, bigint, bigint] & {
        contributor: string;
        accessCount: bigint;
        totalEarned: bigint;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  getContributorCases: TypedContractMethod<
    [contributor: AddressLike],
    [string[]],
    "view"
  >;

  getContributorStats: TypedContractMethod<
    [contributor: AddressLike],
    [
      [bigint, bigint, bigint] & {
        casesUploaded: bigint;
        totalEarned: bigint;
        totalAccesses: bigint;
      }
    ],
    "view"
  >;

  hasAccess: TypedContractMethod<
    [cidHash: BytesLike, user: AddressLike],
    [boolean],
    "view"
  >;

  hasPaid: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  payForAccess: TypedContractMethod<[cidHash: BytesLike], [void], "nonpayable">;

  registerCase: TypedContractMethod<
    [cidHash: BytesLike, contributor: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAccessPrice: TypedContractMethod<
    [_newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accessPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cases"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint] & {
        contributor: string;
        accessCount: bigint;
        totalEarned: bigint;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "contributorCases"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCase"
  ): TypedContractMethod<
    [cidHash: BytesLike],
    [
      [string, bigint, bigint, bigint] & {
        contributor: string;
        accessCount: bigint;
        totalEarned: bigint;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContributorCases"
  ): TypedContractMethod<[contributor: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getContributorStats"
  ): TypedContractMethod<
    [contributor: AddressLike],
    [
      [bigint, bigint, bigint] & {
        casesUploaded: bigint;
        totalEarned: bigint;
        totalAccesses: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasAccess"
  ): TypedContractMethod<
    [cidHash: BytesLike, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasPaid"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payForAccess"
  ): TypedContractMethod<[cidHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerCase"
  ): TypedContractMethod<
    [cidHash: BytesLike, contributor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAccessPrice"
  ): TypedContractMethod<[_newPrice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AccessPriceUpdated"
  ): TypedContractEvent<
    AccessPriceUpdatedEvent.InputTuple,
    AccessPriceUpdatedEvent.OutputTuple,
    AccessPriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CaseAccessed"
  ): TypedContractEvent<
    CaseAccessedEvent.InputTuple,
    CaseAccessedEvent.OutputTuple,
    CaseAccessedEvent.OutputObject
  >;
  getEvent(
    key: "CaseRegistered"
  ): TypedContractEvent<
    CaseRegisteredEvent.InputTuple,
    CaseRegisteredEvent.OutputTuple,
    CaseRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AccessPriceUpdated(uint256,uint256)": TypedContractEvent<
      AccessPriceUpdatedEvent.InputTuple,
      AccessPriceUpdatedEvent.OutputTuple,
      AccessPriceUpdatedEvent.OutputObject
    >;
    AccessPriceUpdated: TypedContractEvent<
      AccessPriceUpdatedEvent.InputTuple,
      AccessPriceUpdatedEvent.OutputTuple,
      AccessPriceUpdatedEvent.OutputObject
    >;

    "CaseAccessed(bytes32,address,address,uint256)": TypedContractEvent<
      CaseAccessedEvent.InputTuple,
      CaseAccessedEvent.OutputTuple,
      CaseAccessedEvent.OutputObject
    >;
    CaseAccessed: TypedContractEvent<
      CaseAccessedEvent.InputTuple,
      CaseAccessedEvent.OutputTuple,
      CaseAccessedEvent.OutputObject
    >;

    "CaseRegistered(bytes32,address,uint256)": TypedContractEvent<
      CaseRegisteredEvent.InputTuple,
      CaseRegisteredEvent.OutputTuple,
      CaseRegisteredEvent.OutputObject
    >;
    CaseRegistered: TypedContractEvent<
      CaseRegisteredEvent.InputTuple,
      CaseRegisteredEvent.OutputTuple,
      CaseRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
