/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ImmiVaultEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AUTO_RELEASE_DURATION"
      | "REQUIRED_APPROVALS"
      | "REQUIRED_FLAGS"
      | "STAKE_AMOUNT"
      | "claimAutoRelease"
      | "contributorEscrows"
      | "escrows"
      | "getContributorEscrows"
      | "getEscrow"
      | "hasVoted"
      | "stakeAndRegister"
      | "treasury"
      | "usdc"
      | "vote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EscrowReleased"
      | "EscrowSlashed"
      | "StakeDeposited"
      | "TrustVote"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "AUTO_RELEASE_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REQUIRED_APPROVALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REQUIRED_FLAGS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STAKE_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimAutoRelease",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contributorEscrows",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "escrows", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getContributorEscrows",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeAndRegister",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BytesLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "AUTO_RELEASE_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REQUIRED_APPROVALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REQUIRED_FLAGS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STAKE_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAutoRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorEscrows",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getContributorEscrows",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeAndRegister",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
}

export namespace EscrowReleasedEvent {
  export type InputTuple = [
    cidHash: BytesLike,
    contributor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    cidHash: string,
    contributor: string,
    amount: bigint
  ];
  export interface OutputObject {
    cidHash: string;
    contributor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowSlashedEvent {
  export type InputTuple = [
    cidHash: BytesLike,
    contributor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    cidHash: string,
    contributor: string,
    amount: bigint
  ];
  export interface OutputObject {
    cidHash: string;
    contributor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeDepositedEvent {
  export type InputTuple = [
    cidHash: BytesLike,
    contributor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    cidHash: string,
    contributor: string,
    amount: bigint
  ];
  export interface OutputObject {
    cidHash: string;
    contributor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrustVoteEvent {
  export type InputTuple = [
    cidHash: BytesLike,
    voter: AddressLike,
    approve: boolean
  ];
  export type OutputTuple = [cidHash: string, voter: string, approve: boolean];
  export interface OutputObject {
    cidHash: string;
    voter: string;
    approve: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ImmiVaultEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): ImmiVaultEscrow;
  waitForDeployment(): Promise<this>;

  interface: ImmiVaultEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AUTO_RELEASE_DURATION: TypedContractMethod<[], [bigint], "view">;

  REQUIRED_APPROVALS: TypedContractMethod<[], [bigint], "view">;

  REQUIRED_FLAGS: TypedContractMethod<[], [bigint], "view">;

  STAKE_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  claimAutoRelease: TypedContractMethod<
    [cidHash: BytesLike],
    [void],
    "nonpayable"
  >;

  contributorEscrows: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  escrows: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint] & {
        contributor: string;
        stakeAmount: bigint;
        stakedAt: bigint;
        status: bigint;
        approvalCount: bigint;
        flagCount: bigint;
      }
    ],
    "view"
  >;

  getContributorEscrows: TypedContractMethod<
    [contributor: AddressLike],
    [string[]],
    "view"
  >;

  getEscrow: TypedContractMethod<
    [cidHash: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint] & {
        contributor: string;
        stakeAmount: bigint;
        stakedAt: bigint;
        status: bigint;
        approvalCount: bigint;
        flagCount: bigint;
      }
    ],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  stakeAndRegister: TypedContractMethod<
    [cidHash: BytesLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  vote: TypedContractMethod<
    [cidHash: BytesLike, approve: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AUTO_RELEASE_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REQUIRED_APPROVALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REQUIRED_FLAGS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STAKE_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimAutoRelease"
  ): TypedContractMethod<[cidHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "contributorEscrows"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint] & {
        contributor: string;
        stakeAmount: bigint;
        stakedAt: bigint;
        status: bigint;
        approvalCount: bigint;
        flagCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContributorEscrows"
  ): TypedContractMethod<[contributor: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [cidHash: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint] & {
        contributor: string;
        stakeAmount: bigint;
        stakedAt: bigint;
        status: bigint;
        approvalCount: bigint;
        flagCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "stakeAndRegister"
  ): TypedContractMethod<[cidHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [cidHash: BytesLike, approve: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EscrowReleased"
  ): TypedContractEvent<
    EscrowReleasedEvent.InputTuple,
    EscrowReleasedEvent.OutputTuple,
    EscrowReleasedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowSlashed"
  ): TypedContractEvent<
    EscrowSlashedEvent.InputTuple,
    EscrowSlashedEvent.OutputTuple,
    EscrowSlashedEvent.OutputObject
  >;
  getEvent(
    key: "StakeDeposited"
  ): TypedContractEvent<
    StakeDepositedEvent.InputTuple,
    StakeDepositedEvent.OutputTuple,
    StakeDepositedEvent.OutputObject
  >;
  getEvent(
    key: "TrustVote"
  ): TypedContractEvent<
    TrustVoteEvent.InputTuple,
    TrustVoteEvent.OutputTuple,
    TrustVoteEvent.OutputObject
  >;

  filters: {
    "EscrowReleased(bytes32,address,uint256)": TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
    EscrowReleased: TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;

    "EscrowSlashed(bytes32,address,uint256)": TypedContractEvent<
      EscrowSlashedEvent.InputTuple,
      EscrowSlashedEvent.OutputTuple,
      EscrowSlashedEvent.OutputObject
    >;
    EscrowSlashed: TypedContractEvent<
      EscrowSlashedEvent.InputTuple,
      EscrowSlashedEvent.OutputTuple,
      EscrowSlashedEvent.OutputObject
    >;

    "StakeDeposited(bytes32,address,uint256)": TypedContractEvent<
      StakeDepositedEvent.InputTuple,
      StakeDepositedEvent.OutputTuple,
      StakeDepositedEvent.OutputObject
    >;
    StakeDeposited: TypedContractEvent<
      StakeDepositedEvent.InputTuple,
      StakeDepositedEvent.OutputTuple,
      StakeDepositedEvent.OutputObject
    >;

    "TrustVote(bytes32,address,bool)": TypedContractEvent<
      TrustVoteEvent.InputTuple,
      TrustVoteEvent.OutputTuple,
      TrustVoteEvent.OutputObject
    >;
    TrustVote: TypedContractEvent<
      TrustVoteEvent.InputTuple,
      TrustVoteEvent.OutputTuple,
      TrustVoteEvent.OutputObject
    >;
  };
}
