import type { CaseRecord } from "@immivault/shared";

export const FAMILY_GC_CASES: CaseRecord[] = [
  // ============================================================
  // APPROVED CASES (45 cases, ~65%)
  // ============================================================
  {
    caseType: "green-card-family",
    countryOfOrigin: "Philippines",
    outcome: "approved",
    year: "2024",
    court: "USCIS Field Office - Chicago",
    narrative:
      "US citizen filed I-130 for spouse who entered on a K-1 visa. Adjustment of status approved after a routine interview where the couple presented joint bank accounts, lease, and wedding photos. No RFE issued.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "Joint bank statements", "Lease agreement", "Wedding photos"],
    keyFactors: "Strong evidence of bona fide marriage with extensive commingling of finances and shared residence.",
    lessonsLearned: "Organize joint financial documents early in the marriage. A well-documented relationship file makes the interview straightforward.",
    timelineMonths: 11,
    lawyerUsed: false,
    formsUsed: ["I-130", "I-485", "I-864", "I-693", "I-765", "I-131"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Mexico",
    outcome: "approved",
    year: "2023",
    court: "USCIS Field Office - Los Angeles",
    narrative:
      "US citizen parent petitioned for unmarried adult son under F2B preference. After a 7-year wait due to visa backlog, the case was processed through consular processing at the US Embassy in Ciudad Juarez. Approved on first interview.",
    documentsUsed: ["I-130", "DS-260", "I-864", "Birth certificate", "Passport", "Police clearance", "Medical exam"],
    keyFactors: "Petitioner maintained continuous US citizenship and sufficient income throughout the long backlog period.",
    lessonsLearned: "F2B backlogs for Mexico are extremely long. Keep all financial documents updated and maintain contact with NVC throughout the wait.",
    timelineMonths: 86,
    lawyerUsed: true,
    formsUsed: ["I-130", "DS-260", "I-864"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "India",
    outcome: "approved",
    year: "2022",
    court: "USCIS Field Office - Newark",
    narrative:
      "US citizen filed for elderly mother as an immediate relative. Case required an RFE for updated I-864 financials since the original submission was over a year old. Approved within 3 weeks of RFE response.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Birth certificate", "Tax returns", "Passport"],
    keyFactors: "Immediate relative category meant no visa backlog. Prompt RFE response kept the case on track.",
    lessonsLearned: "Always submit the most recent tax returns and pay stubs with I-864. Outdated financials almost always trigger an RFE.",
    timelineMonths: 14,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
    rfesReceived: "RFE for updated I-864 with current tax returns and employment verification letter.",
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "China",
    outcome: "approved",
    year: "2024",
    court: "USCIS Field Office - San Francisco",
    narrative:
      "LPR filed I-130 for spouse under F2A preference. Priority date became current after 2 years. Adjustment of status interview included detailed questioning about how the couple met and their daily routines.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "WeChat message logs", "Joint tax returns", "Photos together"],
    keyFactors: "Consistent testimony from both spouses and extensive digital communication records strengthened credibility.",
    lessonsLearned: "Preserve digital communication history such as WeChat or WhatsApp logs. Officers increasingly ask about online communications.",
    timelineMonths: 28,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693", "I-765"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Vietnam",
    outcome: "approved",
    year: "2023",
    court: "US Embassy - Ho Chi Minh City",
    narrative:
      "US citizen petitioned for married daughter under F3 preference. After a 14-year backlog wait, consular interview was conducted in Ho Chi Minh City. Approved with the daughter, her spouse, and two minor children.",
    documentsUsed: ["I-130", "DS-260", "I-864", "Birth certificates", "Marriage certificate", "Police clearances", "Medical exams", "Passport photos"],
    keyFactors: "Petitioner used a joint sponsor to meet the 125% poverty guideline requirement for a family of four derivatives.",
    lessonsLearned: "F3 backlogs can exceed a decade. Plan finances carefully and secure a joint sponsor early if the petitioner's income is borderline.",
    timelineMonths: 172,
    lawyerUsed: true,
    formsUsed: ["I-130", "DS-260", "I-864"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Dominican Republic",
    outcome: "approved",
    year: "2025",
    court: "USCIS Field Office - Miami",
    narrative:
      "US citizen filed for spouse who was present in the US on a tourist visa. Concurrent I-130/I-485 filing. Interview was brief and focused on wedding ceremony details and shared living arrangements.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "Utility bills", "Joint lease", "Affidavits from friends"],
    keyFactors: "Couple had been living together for over a year with substantial shared financial obligations documented.",
    lessonsLearned: "Concurrent filing saves time for immediate relative cases. Gather affidavits from friends and family who can attest to the relationship.",
    timelineMonths: 9,
    lawyerUsed: false,
    formsUsed: ["I-130", "I-485", "I-864", "I-693", "I-765", "I-131"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Haiti",
    outcome: "approved",
    year: "2022",
    court: "USCIS Field Office - Boston",
    narrative:
      "US citizen petitioned for minor child born abroad. DNA test confirmed parentage after initial RFE. Case approved once biological relationship was established through AABB-accredited lab results.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Birth certificate", "DNA test results", "Passport"],
    keyFactors: "DNA evidence conclusively established the parent-child biological relationship after birth certificate discrepancies raised concerns.",
    lessonsLearned: "When birth records are incomplete or inconsistent, proactively submit DNA evidence rather than waiting for an RFE.",
    timelineMonths: 16,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
    rfesReceived: "RFE requesting DNA test to confirm biological parent-child relationship due to inconsistencies in birth certificate.",
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Jamaica",
    outcome: "approved",
    year: "2024",
    court: "USCIS Field Office - Atlanta",
    narrative:
      "LPR petitioned for unmarried adult daughter under F2B preference. After 5-year wait, beneficiary entered through consular processing in Kingston. Approved with waiver of inadmissibility for prior overstay.",
    documentsUsed: ["I-130", "DS-260", "I-864", "I-601", "Birth certificate", "Police clearance", "Evidence of hardship"],
    keyFactors: "Successful I-601 waiver demonstrating extreme hardship to LPR parent if daughter remained inadmissible.",
    lessonsLearned: "Prior immigration violations do not automatically bar approval. A well-documented hardship waiver can overcome inadmissibility grounds.",
    timelineMonths: 64,
    lawyerUsed: true,
    formsUsed: ["I-130", "DS-260", "I-864", "I-601"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Nigeria",
    outcome: "approved",
    year: "2023",
    court: "USCIS Field Office - Houston",
    narrative:
      "US citizen filed for spouse after marriage in Lagos. Spouse entered on CR-1 visa after consular processing. Interview at Houston field office for I-551 stamp was routine with no complications.",
    documentsUsed: ["I-130", "DS-260", "I-864", "Marriage certificate", "Nigerian marriage registry extract", "Photos", "Communication logs"],
    keyFactors: "Thorough documentation of courtship period including travel itineraries, call logs, and social media interactions.",
    lessonsLearned: "For international marriages, document every visit with boarding passes, hotel receipts, and dated photographs.",
    timelineMonths: 13,
    lawyerUsed: false,
    formsUsed: ["I-130", "DS-260", "I-864"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Ghana",
    outcome: "approved",
    year: "2025",
    court: "US Embassy - Accra",
    narrative:
      "US citizen petitioned for sibling under F4 preference. After a 13-year backlog, consular interview in Accra went smoothly. Beneficiary immigrated with spouse and one minor child as derivatives.",
    documentsUsed: ["I-130", "DS-260", "I-864", "Birth certificates", "Marriage certificate", "Police clearances", "Passport", "Financial evidence"],
    keyFactors: "Petitioner's household income of $95,000 comfortably exceeded the poverty guideline for the family size.",
    lessonsLearned: "F4 sibling petitions have the longest backlogs. Start the process as early as possible and maintain updated contact information with NVC.",
    timelineMonths: 160,
    lawyerUsed: false,
    formsUsed: ["I-130", "DS-260", "I-864"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Ethiopia",
    outcome: "approved",
    year: "2022",
    court: "USCIS Field Office - Seattle",
    narrative:
      "US citizen filed for spouse who entered as a refugee and later adjusted status. The couple provided extensive evidence of shared life including a joint mortgage and children's school records listing both parents.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "Joint mortgage documents", "Children's school records", "Tax returns"],
    keyFactors: "Long-established shared household with children and joint property ownership demonstrated a genuine marital relationship.",
    lessonsLearned: "Cases with children and shared property tend to receive less scrutiny. Organize school and medical records listing both parents.",
    timelineMonths: 10,
    lawyerUsed: false,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Brazil",
    outcome: "approved",
    year: "2024",
    court: "USCIS Field Office - Philadelphia",
    narrative:
      "US citizen petitioned for spouse who had been living in the US on an H-4 dependent visa. Adjustment of status interview lasted 20 minutes. Officer was satisfied with joint financial accounts and shared address history.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "H-4 approval notice", "Joint bank statements", "Lease agreements"],
    keyFactors: "Beneficiary maintained valid nonimmigrant status throughout, which simplified the adjustment process.",
    lessonsLearned: "Maintaining valid immigration status before filing for adjustment avoids complications and potential bars to adjustment.",
    timelineMonths: 12,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693", "I-765"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Colombia",
    outcome: "approved",
    year: "2023",
    court: "USCIS Field Office - Dallas",
    narrative:
      "US citizen filed I-130 for father as immediate relative. Father entered on B-2 visitor visa and filed concurrent I-485. Approved after standard interview with no issues raised about the father's prior visits.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Birth certificate", "Father's passport", "Tax returns", "Employment letter"],
    keyFactors: "Clear parent-child relationship documented through birth certificate and petitioner's naturalization records.",
    lessonsLearned: "Parent petitions for immediate relatives are straightforward when documentation is clear. Keep naturalization certificates accessible.",
    timelineMonths: 8,
    lawyerUsed: false,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Ukraine",
    outcome: "approved",
    year: "2024",
    court: "USCIS Field Office - Detroit",
    narrative:
      "US citizen petitioned for spouse who was paroled into the US under Uniting for Ukraine. Adjustment of status was filed based on marriage to US citizen. Approved after interview with interpreter present.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "Parole documents", "Ukrainian passport", "Joint lease"],
    keyFactors: "Parolee status qualified as lawful admission for adjustment purposes under the immediate relative category.",
    lessonsLearned: "Humanitarian parole can serve as a basis for adjustment of status when combined with an approved immediate relative petition.",
    timelineMonths: 10,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693", "I-765"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "South Korea",
    outcome: "approved",
    year: "2022",
    court: "National Benefits Center",
    narrative:
      "US citizen filed I-130 for spouse living in Seoul. Case processed through NVC and consular interview at US Embassy in Seoul. Spouse entered on IR-1 visa and received green card within 2 weeks of arrival.",
    documentsUsed: ["I-130", "DS-260", "I-864", "Marriage certificate", "KakaoTalk chat logs", "Travel itineraries", "Wedding photos"],
    keyFactors: "Couple maintained detailed records of trips between the US and Korea during the long-distance portion of their relationship.",
    lessonsLearned: "For consular processing cases, keep copies of all NVC correspondence and respond to document requests within the given deadlines.",
    timelineMonths: 15,
    lawyerUsed: false,
    formsUsed: ["I-130", "DS-260", "I-864"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Pakistan",
    outcome: "approved",
    year: "2023",
    court: "US Embassy - Islamabad",
    narrative:
      "US citizen petitioned for spouse in an arranged marriage. Consular officer conducted a thorough interview about the courtship and family introductions. Approved after administrative processing cleared within 60 days.",
    documentsUsed: ["I-130", "DS-260", "I-864", "Marriage certificate (Nikah Nama)", "Photos of wedding ceremony", "Family introduction letters", "Communication records"],
    keyFactors: "Detailed testimony about family-facilitated introductions and cultural marriage customs satisfied the officer's inquiries.",
    lessonsLearned: "Arranged marriages receive additional scrutiny but are not inherently suspect. Explain the cultural context clearly and provide family correspondence.",
    timelineMonths: 18,
    lawyerUsed: true,
    formsUsed: ["I-130", "DS-260", "I-864"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Bangladesh",
    outcome: "approved",
    year: "2024",
    court: "USCIS Field Office - NYC",
    narrative:
      "LPR filed for spouse under F2A preference. Priority date became current after 26 months. Stokes interview was ordered due to age difference but both spouses provided consistent, detailed answers.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "Joint bank statements", "Utility bills", "Insurance policies"],
    keyFactors: "Consistent testimony during separated Stokes interview overcame initial concerns about the 18-year age gap.",
    lessonsLearned: "Prepare thoroughly for Stokes interviews by reviewing details of daily life, home layout, and relationship history. Consistency is key.",
    timelineMonths: 30,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
    interviewDetails: "Stokes interview conducted with spouses separated. Both provided matching answers about home details, daily routines, and relationship timeline.",
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Egypt",
    outcome: "approved",
    year: "2022",
    court: "US Embassy - Cairo",
    narrative:
      "US citizen petitioned for mother as immediate relative through consular processing. Case required additional administrative processing due to security checks but was ultimately approved after 4-month delay.",
    documentsUsed: ["I-130", "DS-260", "I-864", "Birth certificate", "Mother's passport", "Tax returns", "Affidavit of support"],
    keyFactors: "Petitioner's strong financial profile and clear biological relationship documented through original birth certificate.",
    lessonsLearned: "Administrative processing delays are common for certain nationalities. Do not panic; follow up with the embassy every 60 days via email.",
    timelineMonths: 20,
    lawyerUsed: false,
    formsUsed: ["I-130", "DS-260", "I-864"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Morocco",
    outcome: "approved",
    year: "2025",
    court: "USCIS Field Office - Denver",
    narrative:
      "US citizen filed for spouse who entered on a J-1 exchange visitor visa. J-1 two-year home residency requirement was waived through a no-objection statement from Morocco. Adjustment approved after waiver clearance.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "I-612", "Marriage certificate", "J-1 waiver approval", "No-objection letter"],
    keyFactors: "Successful J-1 waiver eliminated the two-year home residency requirement that would have barred adjustment.",
    lessonsLearned: "J-1 visa holders must resolve the two-year requirement before adjusting status. Apply for the waiver as early as possible.",
    timelineMonths: 22,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693", "I-612"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Jordan",
    outcome: "approved",
    year: "2023",
    court: "USCIS Field Office - Chicago",
    narrative:
      "US citizen filed for spouse after marriage in Amman. Spouse adjusted status from F-1 student visa. Interview officer asked about plans after graduation and was satisfied the marriage was genuine.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "F-1 visa records", "I-20", "Joint bank account", "Photos"],
    keyFactors: "Beneficiary's valid F-1 status at time of filing and genuine marital relationship supported a clean approval.",
    lessonsLearned: "F-1 students can adjust through marriage to a US citizen. Ensure the I-20 is still valid at the time of filing.",
    timelineMonths: 11,
    lawyerUsed: false,
    formsUsed: ["I-130", "I-485", "I-864", "I-693", "I-765"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "UK",
    outcome: "approved",
    year: "2024",
    court: "USCIS Field Office - Boston",
    narrative:
      "US citizen filed for spouse who was in the US on an L-1 intracompany transfer visa. Couple had been married for 3 years with a child born in the US. Interview was brief and approval came same day.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "Child's birth certificate", "L-1 approval notice", "Joint mortgage"],
    keyFactors: "US-born child and joint home ownership provided overwhelming evidence of a bona fide marriage.",
    lessonsLearned: "Cases with US citizen children and substantial shared assets are typically approved quickly. Bring original documents to the interview.",
    timelineMonths: 8,
    lawyerUsed: false,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Canada",
    outcome: "approved",
    year: "2022",
    court: "USCIS Field Office - Seattle",
    narrative:
      "US citizen petitioned for spouse who had been commuting across the border from Vancouver. Extensive travel records and shared property on both sides of the border documented the relationship well.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "CBP travel records", "Joint property deeds", "Tax returns"],
    keyFactors: "Cross-border travel history and dual property ownership clearly demonstrated an established marital relationship.",
    lessonsLearned: "CBP I-94 travel records are available online and serve as excellent evidence of frequent visits between spouses.",
    timelineMonths: 7,
    lawyerUsed: false,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Germany",
    outcome: "approved",
    year: "2023",
    court: "USCIS Field Office - Phoenix",
    narrative:
      "US citizen filed for spouse who entered on ESTA/VWP. Filed I-130 and I-485 concurrently. Despite entering without a visa, adjustment was approved as immediate relatives of US citizens are exempt from most bars.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "ESTA records", "I-94", "Joint bank account"],
    keyFactors: "VWP entrants can adjust status through marriage to a US citizen under INA 245(a), and the officer confirmed eligibility.",
    lessonsLearned: "Visa Waiver Program entrants are eligible to adjust status as immediate relatives despite the general VWP adjustment bar.",
    timelineMonths: 9,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693", "I-765"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Thailand",
    outcome: "approved",
    year: "2024",
    court: "US Embassy - Bangkok",
    narrative:
      "US citizen petitioned for spouse through consular processing in Bangkok. RFE issued for additional financial evidence as petitioner was self-employed. Joint sponsor resolved the income requirement.",
    documentsUsed: ["I-130", "DS-260", "I-864", "Marriage certificate", "Tax returns", "Self-employment records", "Joint sponsor I-864"],
    keyFactors: "Joint sponsor with stable W-2 employment and income of $72,000 ensured the affidavit of support was sufficient.",
    lessonsLearned: "Self-employed petitioners should secure a joint sponsor early. Consular officers scrutinize self-employment income more carefully.",
    timelineMonths: 14,
    lawyerUsed: true,
    formsUsed: ["I-130", "DS-260", "I-864"],
    rfesReceived: "RFE for additional evidence of income including profit-and-loss statements and a joint sponsor's I-864.",
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Kenya",
    outcome: "approved",
    year: "2025",
    court: "US Embassy - Nairobi",
    narrative:
      "US citizen filed for unmarried minor child under 21. Consular processing in Nairobi completed smoothly. Child entered the US on an IR-2 visa and received green card by mail within 3 weeks.",
    documentsUsed: ["I-130", "DS-260", "I-864", "Birth certificate", "Passport", "Police clearance", "Medical exam", "School records"],
    keyFactors: "Clear documentation of parent-child relationship and child remaining unmarried and under 21 throughout the process.",
    lessonsLearned: "Monitor the child's age carefully. If the child turns 21 before approval, the case may be downgraded to F1 preference with a long backlog.",
    timelineMonths: 12,
    lawyerUsed: false,
    formsUsed: ["I-130", "DS-260", "I-864"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Peru",
    outcome: "approved",
    year: "2022",
    court: "USCIS Field Office - NYC",
    narrative:
      "US citizen filed for spouse who had overstayed a B-2 visa by 8 months. As an immediate relative, the overstay did not bar adjustment. Approved after standard interview with no reference to the overstay.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "I-94 record", "Joint lease", "Utility bills"],
    keyFactors: "Immediate relative status under INA 245(a) permitted adjustment despite the visa overstay, as the beneficiary entered lawfully.",
    lessonsLearned: "Overstays do not bar adjustment for immediate relatives who entered the US with inspection. Consult an attorney to confirm eligibility.",
    timelineMonths: 13,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693", "I-765"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Ecuador",
    outcome: "approved",
    year: "2023",
    court: "USCIS Field Office - Houston",
    narrative:
      "US citizen petitioned for spouse and stepchild. Stepchild qualified as the marriage occurred before the child turned 18. Both cases were approved at a combined interview.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "Stepchild's birth certificate", "Custody documents", "Joint finances"],
    keyFactors: "Marriage occurred when stepchild was 14, well before the age-18 cutoff for establishing a qualifying step-relationship.",
    lessonsLearned: "Step-parent petitions require the marriage to have occurred before the child turned 18. File early to avoid aging-out issues.",
    timelineMonths: 11,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Cuba",
    outcome: "approved",
    year: "2024",
    court: "USCIS Field Office - Miami",
    narrative:
      "US citizen petitioned for spouse who was a Cuban parolee under the Cuban Adjustment Act. One-year physical presence requirement was met. Approved under the special provisions of the CAA.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "Parole documents", "Cuban passport", "Evidence of 1-year presence"],
    keyFactors: "Cuban Adjustment Act provided a unique pathway to adjustment after one year of physical presence in the US.",
    lessonsLearned: "Cuban nationals have special adjustment provisions. Ensure the one-year physical presence requirement is carefully documented.",
    timelineMonths: 14,
    lawyerUsed: false,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Nepal",
    outcome: "approved",
    year: "2025",
    court: "USCIS Field Office - Dallas",
    narrative:
      "US citizen filed for spouse who was on an H-1B work visa. Concurrent I-130/I-485 filed. Interview was waived under USCIS streamlining policy for low-risk cases with strong documentation.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "H-1B approval", "Joint tax returns", "Joint mortgage"],
    keyFactors: "Interview waiver granted due to strong documentary evidence and no fraud indicators in the application.",
    lessonsLearned: "USCIS has been waiving interviews for well-documented marriage cases. Submit thorough evidence upfront to qualify.",
    timelineMonths: 7,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693", "I-765"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Taiwan",
    outcome: "approved",
    year: "2022",
    court: "American Institute in Taiwan - Taipei",
    narrative:
      "US citizen petitioned for elderly father as immediate relative. Consular processing through AIT in Taipei. Father received IR-5 visa after a straightforward interview focusing on the petitioner's finances.",
    documentsUsed: ["I-130", "DS-260", "I-864", "Birth certificate", "Household registration", "Tax returns", "Employment letter"],
    keyFactors: "Petitioner's income of $110,000 well exceeded the poverty guideline and household registration confirmed the parent-child relationship.",
    lessonsLearned: "Taiwanese household registration documents (hukou) are accepted as evidence of family relationships at AIT.",
    timelineMonths: 11,
    lawyerUsed: false,
    formsUsed: ["I-130", "DS-260", "I-864"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Philippines",
    outcome: "approved",
    year: "2023",
    court: "US Embassy - Manila",
    narrative:
      "US citizen petitioned for married son under F3 preference. After 12-year backlog, interview in Manila was conducted. Son immigrated with wife and three children as derivative beneficiaries.",
    documentsUsed: ["I-130", "DS-260", "I-864", "Birth certificates", "Marriage certificate", "NSO documents", "Police clearances", "Medical exams"],
    keyFactors: "Petitioner used assets including a paid-off home valued at $350,000 to supplement income on the I-864.",
    lessonsLearned: "Assets can be used at 1/5 of their value (1/3 for sponsors) to meet the I-864 income requirement. Include property appraisals.",
    timelineMonths: 148,
    lawyerUsed: true,
    formsUsed: ["I-130", "DS-260", "I-864"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Mexico",
    outcome: "approved",
    year: "2024",
    court: "US Consulate - Ciudad Juarez",
    narrative:
      "US citizen filed for spouse who had a prior deportation. I-212 permission to reapply and I-601 waiver were both approved before the consular interview. Visa issued after administrative processing.",
    documentsUsed: ["I-130", "DS-260", "I-864", "I-212", "I-601", "Marriage certificate", "Hardship evidence", "Children's records"],
    keyFactors: "Approved I-212 and I-601 waiver based on extreme hardship to US citizen spouse and three US citizen children.",
    lessonsLearned: "Prior deportations require I-212 and potentially I-601 waivers. Document hardship to qualifying relatives thoroughly.",
    timelineMonths: 36,
    lawyerUsed: true,
    formsUsed: ["I-130", "DS-260", "I-864", "I-212", "I-601"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "India",
    outcome: "approved",
    year: "2025",
    court: "USCIS Field Office - San Francisco",
    narrative:
      "US citizen filed for spouse who was on H-4 status. EAD was obtained through I-765 while I-485 was pending. Case approved 9 months after filing with no RFE or interview complications.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "H-4 approval", "Joint investments", "Insurance policies"],
    keyFactors: "Clean immigration history, strong financials, and well-organized petition led to efficient processing.",
    lessonsLearned: "Thorough initial filings reduce processing times. Include all supporting documents upfront rather than waiting for RFEs.",
    timelineMonths: 9,
    lawyerUsed: false,
    formsUsed: ["I-130", "I-485", "I-864", "I-693", "I-765", "I-131"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "South Africa",
    outcome: "approved",
    year: "2023",
    court: "USCIS Field Office - Atlanta",
    narrative:
      "US citizen filed for spouse after a 2-year long-distance relationship. Couple provided detailed WhatsApp history, flight records for 6 visits, and hotel receipts. Approved after a 30-minute interview.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "WhatsApp logs", "Flight itineraries", "Hotel receipts", "Photos"],
    keyFactors: "Extensive travel records documenting 6 trips over 2 years and continuous daily communication established a genuine relationship.",
    lessonsLearned: "Long-distance relationships require more documentation effort. Save all travel receipts and communication records from the start.",
    timelineMonths: 12,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693", "I-765"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "France",
    outcome: "approved",
    year: "2024",
    court: "National Benefits Center",
    narrative:
      "US citizen filed I-130 for spouse for consular processing at US Embassy in Paris. NVC processing took 5 months. Paris interview was brief and visa was issued the same week.",
    documentsUsed: ["I-130", "DS-260", "I-864", "Marriage certificate (livret de famille)", "Tax returns", "Photos", "Travel records"],
    keyFactors: "French livret de famille served as strong official evidence of the marriage alongside the acte de mariage.",
    lessonsLearned: "European civil documents are generally well-accepted. Provide certified translations alongside originals.",
    timelineMonths: 10,
    lawyerUsed: false,
    formsUsed: ["I-130", "DS-260", "I-864"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Japan",
    outcome: "approved",
    year: "2022",
    court: "USCIS Field Office - Los Angeles",
    narrative:
      "US citizen filed for spouse who was on an E-2 treaty investor dependent visa. Adjustment interview was smooth. Officer focused on verifying the marriage certificate from the ward office in Tokyo.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Koseki tohon (family register)", "Marriage certificate", "Joint tax return", "Photos"],
    keyFactors: "Japanese koseki tohon provided comprehensive family relationship documentation accepted by USCIS.",
    lessonsLearned: "Japanese family register (koseki) documents are highly detailed and serve as excellent primary evidence of relationships.",
    timelineMonths: 10,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Philippines",
    outcome: "approved",
    year: "2025",
    court: "USCIS Field Office - Chicago",
    narrative:
      "LPR filed I-130 for spouse under F2A. After 2-year wait, adjustment interview was scheduled. Officer asked about prior marriages of both parties. Approved after verifying divorce decrees were final.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "Prior divorce decrees", "CENOMAR from PSA", "Joint finances"],
    keyFactors: "Certificate of No Marriage (CENOMAR) from Philippine Statistics Authority confirmed no prior undissolved marriages in the Philippines.",
    lessonsLearned: "CENOMAR from PSA is essential for Filipino nationals to prove they were free to marry. Order it well in advance.",
    timelineMonths: 26,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "China",
    outcome: "approved",
    year: "2023",
    court: "US Consulate - Guangzhou",
    narrative:
      "US citizen petitioned for unmarried adult child under F1 preference. After 8-year backlog, consular interview in Guangzhou was completed. Beneficiary demonstrated ties to the US through prior education.",
    documentsUsed: ["I-130", "DS-260", "I-864", "Birth certificate", "Hukou", "University transcripts", "Tax returns", "Police clearance"],
    keyFactors: "Beneficiary's prior US education (F-1 student at UCLA) and maintained unmarried status throughout the backlog.",
    lessonsLearned: "F1 preference beneficiaries must remain unmarried. Any marriage during the backlog period will void the petition.",
    timelineMonths: 98,
    lawyerUsed: true,
    formsUsed: ["I-130", "DS-260", "I-864"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Vietnam",
    outcome: "approved",
    year: "2024",
    court: "USCIS Field Office - Houston",
    narrative:
      "US citizen filed for spouse after marriage in Saigon. Spouse entered on CR-1 visa. Conditions were removed 2 years later by filing I-751 with evidence of ongoing marriage. Unconditional green card issued.",
    documentsUsed: ["I-130", "DS-260", "I-864", "I-751", "Marriage certificate", "Joint mortgage", "Children's birth certificates", "Tax returns"],
    keyFactors: "Birth of two children during the conditional residence period provided strong evidence of an ongoing bona fide marriage.",
    lessonsLearned: "File I-751 to remove conditions during the 90-day window before the green card expires. Late filings can result in removal proceedings.",
    timelineMonths: 38,
    lawyerUsed: false,
    formsUsed: ["I-130", "DS-260", "I-864", "I-751"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Nigeria",
    outcome: "approved",
    year: "2025",
    court: "USCIS Field Office - Newark",
    narrative:
      "US citizen filed for sibling under F4 preference. After 15-year wait, sibling adjusted status in the US as she had maintained valid H-1B status throughout. No consular processing needed.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Birth certificates", "H-1B approvals", "Tax returns", "Employment records"],
    keyFactors: "Beneficiary's continuous lawful H-1B status allowed adjustment in the US rather than returning to Nigeria for consular processing.",
    lessonsLearned: "Maintaining valid nonimmigrant status during long F4 backlogs provides the option to adjust domestically when the priority date becomes current.",
    timelineMonths: 182,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Colombia",
    outcome: "approved",
    year: "2022",
    court: "USCIS Field Office - Miami",
    narrative:
      "US citizen petitioned for spouse. Stokes interview ordered due to short courtship period of 3 months before marriage. Both spouses answered consistently about their relationship, and the case was approved.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "Joint lease", "Text messages", "Social media posts"],
    keyFactors: "Consistent and detailed answers during the Stokes interview about how they met, their wedding, and daily life overcame fraud concerns.",
    lessonsLearned: "Short courtships trigger additional scrutiny. Be prepared for a Stokes interview and review all relationship details with your spouse beforehand.",
    timelineMonths: 15,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
    interviewDetails: "Stokes interview ordered due to 3-month courtship. Spouses separated and questioned individually for 45 minutes each.",
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Mexico",
    outcome: "approved",
    year: "2025",
    court: "USCIS Field Office - Phoenix",
    narrative:
      "US citizen filed for minor child born in Mexico. Child entered on IR-2 visa after consular processing in Ciudad Juarez. Green card arrived within 2 weeks of the child's entry into the US.",
    documentsUsed: ["I-130", "DS-260", "I-864", "Birth certificate", "DNA test", "Passport", "Medical exam", "School records"],
    keyFactors: "DNA test proactively submitted with the petition eliminated potential delays from an RFE for parentage verification.",
    lessonsLearned: "Proactively include DNA evidence for children born out of wedlock or where the birth certificate lists only one parent.",
    timelineMonths: 10,
    lawyerUsed: false,
    formsUsed: ["I-130", "DS-260", "I-864"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Dominican Republic",
    outcome: "approved",
    year: "2024",
    court: "USCIS Field Office - NYC",
    narrative:
      "LPR filed for unmarried adult son under F2B. After 6-year backlog, adjustment interview was scheduled. Son had maintained valid TPS status throughout. Approved with no RFE.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Birth certificate", "TPS approval notices", "Employment records", "Tax returns"],
    keyFactors: "TPS provided lawful status and work authorization during the multi-year F2B backlog.",
    lessonsLearned: "TPS holders should explore family-based petitions as a path to permanent residence while maintaining their TPS status.",
    timelineMonths: 74,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Brazil",
    outcome: "approved",
    year: "2023",
    court: "USCIS Field Office - Philadelphia",
    narrative:
      "US citizen filed for spouse who entered without inspection but qualified for 245(i) adjustment under a prior labor certification filed before April 2001. Penalty fee paid and case approved.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "Prior labor certification", "Proof of physical presence April 2001", "Penalty fee payment"],
    keyFactors: "Qualifying prior petition filed before April 30, 2001 and physical presence on December 21, 2000 enabled 245(i) adjustment.",
    lessonsLearned: "245(i) grandfathering remains available for those who can prove a qualifying petition was filed before the deadline. Preserve all old immigration records.",
    timelineMonths: 18,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Honduras",
    outcome: "approved",
    year: "2023",
    court: "USCIS Field Office - Denver",
    narrative:
      "US citizen filed for spouse who entered the US as an unaccompanied minor and was granted Special Immigrant Juvenile Status years earlier. Adjustment through marriage to US citizen processed smoothly with no RFE.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "SIJS approval", "Joint bank account", "Lease"],
    keyFactors: "Prior SIJS grant established lawful status, and marriage to US citizen provided a straightforward path to permanent residence.",
    lessonsLearned: "Former SIJS recipients who marry US citizens can adjust status as immediate relatives. Prior immigration history should be fully documented.",
    timelineMonths: 10,
    lawyerUsed: false,
    formsUsed: ["I-130", "I-485", "I-864", "I-693", "I-765"],
  },
  // ============================================================
  // DENIED CASES (10 cases, ~15%)
  // ============================================================
  {
    caseType: "green-card-family",
    countryOfOrigin: "India",
    outcome: "denied",
    year: "2023",
    court: "USCIS Field Office - San Francisco",
    narrative:
      "US citizen filed for spouse but the Stokes interview revealed major inconsistencies. Spouses gave contradictory answers about their living situation, wedding guests, and daily routines. Case denied for failure to establish bona fide marriage.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "Limited joint documents"],
    keyFactors: "Inconsistent testimony during Stokes interview and minimal joint financial evidence led to a finding of marriage fraud.",
    lessonsLearned: "USCIS takes Stokes interviews seriously. Contradictory answers about basic household details are strong indicators of fraud.",
    timelineMonths: 14,
    lawyerUsed: false,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
    denialReasons: "Failure to establish bona fide marriage under INA 204(c). Inconsistent testimony and lack of commingled finances.",
    interviewDetails: "Stokes interview revealed husband could not name wife's employer, and wife stated they had separate bedrooms.",
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Philippines",
    outcome: "denied",
    year: "2022",
    court: "USCIS Field Office - Los Angeles",
    narrative:
      "LPR filed for spouse under F2A but petitioner's tax returns showed income below the poverty guideline. No joint sponsor was submitted and the RFE response was insufficient. Case denied for inadequate affidavit of support.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "Tax returns showing $18,000 income"],
    keyFactors: "Petitioner's income of $18,000 was below the 125% poverty guideline for a household of 4. No joint sponsor was offered.",
    lessonsLearned: "Always calculate the poverty guideline for your household size before filing. Secure a joint sponsor if income is insufficient.",
    timelineMonths: 16,
    lawyerUsed: false,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
    denialReasons: "Insufficient affidavit of support. Petitioner's income below 125% poverty guideline with no joint sponsor.",
    rfesReceived: "RFE for updated I-864 with sufficient income or joint sponsor. Response submitted without joint sponsor.",
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Bangladesh",
    outcome: "denied",
    year: "2024",
    court: "US Embassy - Dhaka",
    narrative:
      "US citizen filed for spouse in an arranged marriage. Consular officer found the couple unable to communicate in any shared language during the interview. Visa refused under INA 212(a)(6)(C) for misrepresentation.",
    documentsUsed: ["I-130", "DS-260", "I-864", "Marriage certificate", "Photos", "Limited communication records"],
    keyFactors: "Couple had no common language and could not demonstrate any meaningful communication history.",
    lessonsLearned: "Consular officers expect couples to be able to communicate. Language barriers combined with lack of communication evidence raise serious fraud concerns.",
    timelineMonths: 18,
    lawyerUsed: false,
    formsUsed: ["I-130", "DS-260", "I-864"],
    denialReasons: "INA 212(a)(6)(C)(i) - Fraud or willful misrepresentation. Officer determined marriage was not bona fide.",
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Ghana",
    outcome: "denied",
    year: "2023",
    court: "USCIS Field Office - NYC",
    narrative:
      "US citizen filed for spouse but USCIS discovered the petitioner had a prior I-130 approved for a different spouse that was later found to be fraudulent. Petition denied under the marriage fraud bar.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "Joint documents"],
    keyFactors: "INA 204(c) marriage fraud bar applied because petitioner's prior marriage-based petition was determined to be fraudulent.",
    lessonsLearned: "A finding of marriage fraud permanently bars the individual from benefiting from future marriage-based petitions unless the bar is overcome.",
    timelineMonths: 12,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
    denialReasons: "INA 204(c) marriage fraud bar. Prior petition for different spouse found fraudulent. Permanent bar applies.",
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Haiti",
    outcome: "denied",
    year: "2024",
    court: "USCIS Field Office - Miami",
    narrative:
      "US citizen filed for sibling under F4. However, petitioner could not establish a qualifying sibling relationship because the birth certificates showed different mothers and the father had not legitimated the beneficiary under Haitian law.",
    documentsUsed: ["I-130", "Birth certificates", "Baptismal records", "Affidavits"],
    keyFactors: "Failure to establish legitimation of the half-sibling under the law of Haiti at the time of the father's actions.",
    lessonsLearned: "Half-sibling relationships through fathers require proof of legitimation under the relevant country's law. Research legitimation requirements early.",
    timelineMonths: 8,
    lawyerUsed: false,
    formsUsed: ["I-130"],
    denialReasons: "Failure to establish qualifying family relationship. No evidence of legitimation under Haitian civil code.",
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Mexico",
    outcome: "denied",
    year: "2022",
    court: "US Consulate - Ciudad Juarez",
    narrative:
      "US citizen filed for spouse who had a prior removal order and 10-year bar. I-212 application to reapply was denied due to insufficient evidence of extreme hardship. Consular interview was therefore refused.",
    documentsUsed: ["I-130", "DS-260", "I-864", "I-212", "Marriage certificate", "Hardship letters"],
    keyFactors: "I-212 denied because hardship evidence was limited to general claims without medical, financial, or psychological documentation.",
    lessonsLearned: "I-212 waiver applications require specific, well-documented evidence of extreme hardship. General statements about missing a spouse are insufficient.",
    timelineMonths: 24,
    lawyerUsed: true,
    formsUsed: ["I-130", "DS-260", "I-864", "I-212"],
    denialReasons: "I-212 denied for insufficient hardship evidence. Without approved I-212, consular interview could not proceed.",
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Pakistan",
    outcome: "denied",
    year: "2025",
    court: "US Embassy - Islamabad",
    narrative:
      "US citizen filed for spouse but administrative processing revealed the beneficiary had provided false information about prior visa applications. Visa permanently refused under INA 212(a)(6)(C) for material misrepresentation.",
    documentsUsed: ["I-130", "DS-260", "I-864", "Marriage certificate", "Prior visa applications"],
    keyFactors: "Beneficiary had claimed to be single on a prior B-1 visa application while actually being married. Material misrepresentation finding.",
    lessonsLearned: "Inconsistencies between prior visa applications and current petitions are thoroughly checked. Always disclose prior applications truthfully.",
    timelineMonths: 22,
    lawyerUsed: true,
    formsUsed: ["I-130", "DS-260", "I-864"],
    denialReasons: "INA 212(a)(6)(C)(i) - Material misrepresentation on prior visa application regarding marital status.",
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Nigeria",
    outcome: "denied",
    year: "2023",
    court: "USCIS Field Office - Houston",
    narrative:
      "LPR petitioned for unmarried daughter under F2B but daughter married during the backlog period, which automatically revoked the petition. USCIS denied the I-485 when marriage was discovered during the interview.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Birth certificate", "Marriage certificate discovered"],
    keyFactors: "Beneficiary's marriage during the F2B backlog period automatically revoked the underlying I-130 petition.",
    lessonsLearned: "F2B beneficiaries must remain unmarried. Marriage during the backlog period voids the petition entirely with no option to reinstate.",
    timelineMonths: 48,
    lawyerUsed: false,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
    denialReasons: "Automatic revocation of I-130 under INA 203(g). Beneficiary married during F2B backlog, disqualifying the preference category.",
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "China",
    outcome: "denied",
    year: "2024",
    court: "USCIS Field Office - San Francisco",
    narrative:
      "US citizen filed for spouse but the I-693 medical exam revealed the beneficiary had untreated Class A tuberculosis. Case denied when beneficiary failed to complete the required treatment protocol within the given timeframe.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "Medical records"],
    keyFactors: "Class A medical condition (active TB) is a ground of inadmissibility. Beneficiary did not complete treatment within the allowed period.",
    lessonsLearned: "Complete all required medical treatments before the I-693 expires. Class A conditions must be resolved before adjustment can be approved.",
    timelineMonths: 18,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
    denialReasons: "Inadmissible under INA 212(a)(1)(A)(i) - Class A medical condition (active tuberculosis). Failed to complete treatment.",
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Jamaica",
    outcome: "denied",
    year: "2022",
    court: "USCIS Field Office - Atlanta",
    narrative:
      "US citizen filed for spouse but background check revealed a prior criminal conviction for an aggravated felony drug trafficking offense. Beneficiary found inadmissible with no available waiver.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "Court records"],
    keyFactors: "Aggravated felony drug conviction is a permanent ground of inadmissibility with no waiver available under current law.",
    lessonsLearned: "Certain criminal convictions create permanent bars to immigration benefits. Consult an immigration attorney before filing if there is any criminal history.",
    timelineMonths: 10,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
    denialReasons: "Inadmissible under INA 212(a)(2)(A) - Controlled substance trafficking conviction. No waiver available for aggravated felony.",
  },
  // ============================================================
  // PENDING CASES (11 cases, ~15%)
  // ============================================================
  {
    caseType: "green-card-family",
    countryOfOrigin: "Philippines",
    outcome: "pending",
    year: "2024",
    court: "National Benefits Center",
    narrative:
      "US citizen filed I-130 for sibling under F4. Petition was approved but the priority date is not yet current due to a 23-year backlog for Philippines F4. Case remains pending at NVC awaiting visa availability.",
    documentsUsed: ["I-130", "Birth certificates", "Petitioner's naturalization certificate"],
    keyFactors: "Philippines F4 backlog is the longest of any category, with current wait times exceeding 20 years.",
    lessonsLearned: "F4 petitions for Philippine siblings require extraordinary patience. File as early as possible and consider alternative pathways.",
    timelineMonths: 14,
    lawyerUsed: false,
    formsUsed: ["I-130"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Mexico",
    outcome: "pending",
    year: "2023",
    court: "National Benefits Center",
    narrative:
      "LPR filed I-130 for married son under F2B preference. I-130 approved but priority date backlog for Mexico F2B is approximately 22 years. Family continues to wait for the priority date to become current.",
    documentsUsed: ["I-130", "Birth certificate", "LPR card", "Marriage certificate of son"],
    keyFactors: "Mexico F2B category has severe backlogs. Petitioner is considering naturalizing to potentially move the case to F3.",
    lessonsLearned: "If eligible, LPR petitioners should consider naturalizing. While F3 also has backlogs, the overall strategy may improve with citizenship.",
    timelineMonths: 30,
    lawyerUsed: true,
    formsUsed: ["I-130"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "India",
    outcome: "pending",
    year: "2024",
    court: "USCIS Field Office - Chicago",
    narrative:
      "US citizen filed for spouse. I-130 and I-485 submitted concurrently. Case has been pending for 14 months with no interview scheduled. Multiple service request inquiries have yielded only automated responses.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "Joint finances"],
    keyFactors: "Processing delays at Chicago field office have pushed immediate relative cases beyond 12 months with no interview dates.",
    lessonsLearned: "Contact your congressperson's office for a congressional inquiry if processing exceeds normal timeframes significantly.",
    timelineMonths: 14,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693", "I-765", "I-131"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Vietnam",
    outcome: "pending",
    year: "2025",
    court: "USCIS Field Office - Dallas",
    narrative:
      "US citizen filed for elderly mother as immediate relative. I-485 filed but medical exam revealed a condition requiring specialist evaluation. Case placed on hold pending updated I-693 with specialist clearance.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Birth certificate", "Passport", "Medical records"],
    keyFactors: "I-693 medical exam flagged a potential Class B condition requiring further evaluation by a specialist.",
    lessonsLearned: "Schedule the civil surgeon appointment early and address any medical issues proactively before they delay the case.",
    timelineMonths: 6,
    lawyerUsed: false,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
    rfesReceived: "RFE for updated I-693 with specialist evaluation for cardiac condition noted during initial exam.",
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Ethiopia",
    outcome: "pending",
    year: "2024",
    court: "US Embassy - Addis Ababa",
    narrative:
      "US citizen petitioned for spouse through consular processing. Case has been in administrative processing for over 8 months following the consular interview. No timeline provided by the embassy.",
    documentsUsed: ["I-130", "DS-260", "I-864", "Marriage certificate", "Passport", "Police clearance"],
    keyFactors: "Extended administrative processing with no clear timeline. Embassy responses indicate security background checks are ongoing.",
    lessonsLearned: "Administrative processing can extend cases indefinitely. Maintain regular follow-up every 60 days and consider contacting your senator's office.",
    timelineMonths: 20,
    lawyerUsed: true,
    formsUsed: ["I-130", "DS-260", "I-864"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Cuba",
    outcome: "pending",
    year: "2025",
    court: "USCIS Field Office - Miami",
    narrative:
      "US citizen filed for sibling under F4 preference. I-130 recently approved. Priority date is 2025 and current wait for Cuba F4 is approximately 8 years. Case is pending at NVC.",
    documentsUsed: ["I-130", "Birth certificates", "Naturalization certificate"],
    keyFactors: "Cuba F4 backlog is shorter than some countries but still represents a multi-year wait.",
    lessonsLearned: "File the I-130 as early as possible to establish the priority date. The wait begins from the filing date, not the approval date.",
    timelineMonths: 4,
    lawyerUsed: false,
    formsUsed: ["I-130"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "South Korea",
    outcome: "pending",
    year: "2024",
    court: "National Benefits Center",
    narrative:
      "LPR filed I-130 for spouse under F2A preference. Petition approved but priority date is not yet current. Beneficiary continues to wait in Seoul and maintains contact with NVC.",
    documentsUsed: ["I-130", "Marriage certificate", "LPR card copy", "Birth certificate"],
    keyFactors: "F2A category has a moderate backlog. Petitioner is studying for the citizenship test to potentially convert this to an immediate relative case.",
    lessonsLearned: "LPRs should pursue naturalization when eligible, as it eliminates the F2A backlog by converting the spouse to an immediate relative.",
    timelineMonths: 18,
    lawyerUsed: false,
    formsUsed: ["I-130"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Ukraine",
    outcome: "pending",
    year: "2025",
    court: "USCIS Field Office - Denver",
    narrative:
      "US citizen filed for spouse who was paroled under Uniting for Ukraine. I-485 pending and EAD issued. Interview has not yet been scheduled and the case is in the normal processing queue.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "Parole documents", "Joint bank account"],
    keyFactors: "Case filed 5 months ago and is within normal processing times. Beneficiary is working on EAD while waiting.",
    lessonsLearned: "Apply for the EAD concurrently with I-485 so the beneficiary can work while waiting for the green card interview.",
    timelineMonths: 5,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693", "I-765", "I-131"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Egypt",
    outcome: "pending",
    year: "2024",
    court: "US Embassy - Cairo",
    narrative:
      "US citizen filed for unmarried adult child under F1 preference. I-130 approved 6 years ago but priority date for Egypt remains retrogressed. NVC holds the case in a pending status awaiting visa number availability.",
    documentsUsed: ["I-130", "Birth certificate", "Naturalization certificate", "Passport"],
    keyFactors: "F1 category backlog for Egypt is approximately 9 years. Beneficiary must remain unmarried throughout the wait.",
    lessonsLearned: "Monitor the monthly visa bulletin carefully. Priority dates can retrogress, extending wait times beyond initial estimates.",
    timelineMonths: 72,
    lawyerUsed: true,
    formsUsed: ["I-130"],
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Dominican Republic",
    outcome: "pending",
    year: "2025",
    court: "USCIS Field Office - Boston",
    narrative:
      "US citizen filed for spouse. Interview was conducted 3 months ago but officer requested additional evidence of bona fide marriage. Couple submitted supplemental documents and awaits a decision.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "Joint finances", "Supplemental evidence packet"],
    keyFactors: "Officer was not fully satisfied at interview and issued a request for additional evidence including more joint financial documents.",
    lessonsLearned: "If the officer requests additional evidence at the interview, respond promptly and thoroughly. Delays in responding can lead to denial.",
    timelineMonths: 11,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693"],
    rfesReceived: "Post-interview RFE for additional evidence of bona fide marriage including joint insurance policies and additional affidavits.",
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Thailand",
    outcome: "pending",
    year: "2024",
    court: "National Benefits Center",
    narrative:
      "US citizen filed I-130 for married daughter under F3 preference. Petition approved and forwarded to NVC. Current F3 backlog is approximately 11 years. Case is in long-term pending status.",
    documentsUsed: ["I-130", "Birth certificate", "Daughter's marriage certificate", "Naturalization certificate"],
    keyFactors: "F3 category has substantial backlogs. Daughter's family of 4 will require robust financial sponsorship when priority date becomes current.",
    lessonsLearned: "Begin gathering financial documents and identifying potential joint sponsors well before the priority date becomes current.",
    timelineMonths: 36,
    lawyerUsed: false,
    formsUsed: ["I-130"],
  },
  // ============================================================
  // APPEALED CASES (2 cases)
  // ============================================================
  {
    caseType: "green-card-family",
    countryOfOrigin: "Peru",
    outcome: "appealed",
    year: "2023",
    court: "USCIS Field Office - Los Angeles",
    narrative:
      "US citizen filed for spouse but I-130 was denied based on a finding of marriage fraud. Case appealed to the Board of Immigration Appeals. Appeal is pending with oral argument requested.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "Appeal brief", "Additional evidence of relationship"],
    keyFactors: "Original denial based on alleged inconsistencies during interview. Appeal argues the officer misinterpreted cultural communication differences.",
    lessonsLearned: "Appeal denials promptly within the 30-day deadline. Submit a detailed brief addressing each ground of denial with new supporting evidence.",
    timelineMonths: 24,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693", "I-290B"],
    appealDetails: "I-290B filed within 30 days. Appeal brief argues cultural misunderstanding during interview. Additional affidavits and evidence submitted. Oral argument requested.",
    denialReasons: "Original denial for failure to establish bona fide marriage based on perceived interview inconsistencies.",
  },
  {
    caseType: "green-card-family",
    countryOfOrigin: "Morocco",
    outcome: "appealed",
    year: "2024",
    court: "USCIS Field Office - Newark",
    narrative:
      "LPR filed for spouse under F2A but I-130 denied because USCIS concluded the marriage was entered into solely for immigration purposes. Motion to reopen filed with new evidence of cohabitation and a newborn child.",
    documentsUsed: ["I-130", "I-485", "Marriage certificate", "Motion to reopen", "Child's birth certificate", "New joint financial evidence"],
    keyFactors: "Birth of a child after the denial provided significant new evidence of an ongoing genuine marital relationship.",
    lessonsLearned: "Motions to reopen must present new, material evidence not available at the time of the original decision. Life events like childbirth can be compelling.",
    timelineMonths: 20,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-290B"],
    appealDetails: "Motion to reopen filed with I-290B. New evidence includes child's birth certificate, pediatrician records listing both parents, and updated joint financial documents.",
    denialReasons: "Original denial under INA 204(c) for marriage entered into solely for immigration benefits.",
  },
  // ============================================================
  // WITHDRAWN CASE (1 case)
  // ============================================================
  {
    caseType: "green-card-family",
    countryOfOrigin: "Ecuador",
    outcome: "withdrawn",
    year: "2022",
    court: "USCIS Field Office - Houston",
    narrative:
      "US citizen filed for spouse but couple divorced during the pendency of the case. Petitioner voluntarily withdrew the I-130 petition after the divorce was finalized in Texas family court.",
    documentsUsed: ["I-130", "I-485", "Marriage certificate", "Divorce decree", "Withdrawal letter"],
    keyFactors: "Divorce terminated the qualifying relationship, making the petition no longer viable.",
    lessonsLearned: "Notify USCIS promptly if circumstances change. Withdrawing a petition is preferable to having it denied for fraud.",
    timelineMonths: 8,
    lawyerUsed: false,
    formsUsed: ["I-130", "I-485", "I-864"],
  },
  // ============================================================
  // REMANDED CASE (1 case)
  // ============================================================
  {
    caseType: "green-card-family",
    countryOfOrigin: "Nepal",
    outcome: "remanded",
    year: "2024",
    court: "USCIS Field Office - Detroit",
    narrative:
      "US citizen filed for spouse but I-130 denied for insufficient evidence of bona fide marriage. AAO remanded the case to the field office for a new interview, finding the original officer failed to consider submitted evidence.",
    documentsUsed: ["I-130", "I-485", "I-864", "I-693", "Marriage certificate", "Appeal brief", "Evidence inventory"],
    keyFactors: "AAO found that the field office failed to review and consider multiple exhibits submitted with the original application.",
    lessonsLearned: "If evidence was submitted but not considered, an appeal can result in a remand. Keep detailed records of every document submitted with proof of receipt.",
    timelineMonths: 22,
    lawyerUsed: true,
    formsUsed: ["I-130", "I-485", "I-864", "I-693", "I-290B"],
    appealDetails: "AAO sustained the appeal and remanded to the local field office for de novo review. New interview ordered with instructions to consider all submitted exhibits.",
    denialReasons: "Original denial for insufficient evidence of bona fide marriage. AAO found officer failed to consider 14 exhibits in the record.",
  },
];
